/*
 * channel_colapse.h
 *
 *Generated by matlab
 */ 


#ifndef CHANNEL_COLAPSE_H_
#define CHANNEL_COLAPSE_H_



//Image: channel_colapse   size: 6x6 pixels 

const RGBcolor_t channel_colapse_data[36];

const bitmap_t channel_colapse = {.xSize = 6, .ySize = 6, .data = channel_colapse_data};

/*The image data encoded in RGBcolor_t*/
const RGBcolor_t channel_colapse_data[36] = {	
			{ .red = 0xff, .green = 0xff, .blue = 0xff}, 
			{ .red = 0xff, .green = 0xff, .blue = 0xff}, 
			{ .red = 0xff, .green = 0xff, .blue = 0xff}, 
			{ .red = 0xff, .green = 0xff, .blue = 0xff}, 
			{ .red = 0xbf, .green = 0xbf, .blue = 0xbf}, 
			{ .red = 0x88, .green = 0x88, .blue = 0x88}, 

			{ .red = 0xff, .green = 0xff, .blue = 0xff}, 
			{ .red = 0xff, .green = 0xff, .blue = 0xff}, 
			{ .red = 0xff, .green = 0xff, .blue = 0xff}, 
			{ .red = 0xbd, .green = 0xbd, .blue = 0xbd}, 
			{ .red = 0x2b, .green = 0x2b, .blue = 0x2b}, 
			{ .red = 0x26, .green = 0x26, .blue = 0x26}, 

			{ .red = 0xff, .green = 0xff, .blue = 0xff}, 
			{ .red = 0xff, .green = 0xff, .blue = 0xff}, 
			{ .red = 0xbd, .green = 0xbd, .blue = 0xbd}, 
			{ .red = 0x2b, .green = 0x2b, .blue = 0x2b}, 
			{ .red = 0x58, .green = 0x58, .blue = 0x58}, 
			{ .red = 0x26, .green = 0x26, .blue = 0x26}, 

			{ .red = 0xff, .green = 0xff, .blue = 0xff}, 
			{ .red = 0xbd, .green = 0xbd, .blue = 0xbd}, 
			{ .red = 0x2b, .green = 0x2b, .blue = 0x2b}, 
			{ .red = 0x58, .green = 0x58, .blue = 0x58}, 
			{ .red = 0x59, .green = 0x59, .blue = 0x59}, 
			{ .red = 0x26, .green = 0x26, .blue = 0x26}, 

			{ .red = 0xbd, .green = 0xbd, .blue = 0xbd}, 
			{ .red = 0x2b, .green = 0x2b, .blue = 0x2b}, 
			{ .red = 0x58, .green = 0x58, .blue = 0x58}, 
			{ .red = 0x59, .green = 0x59, .blue = 0x59}, 
			{ .red = 0x59, .green = 0x59, .blue = 0x59}, 
			{ .red = 0x26, .green = 0x26, .blue = 0x26}, 

			{ .red = 0x88, .green = 0x88, .blue = 0x88}, 
			{ .red = 0x26, .green = 0x26, .blue = 0x26}, 
			{ .red = 0x26, .green = 0x26, .blue = 0x26}, 
			{ .red = 0x26, .green = 0x26, .blue = 0x26}, 
			{ .red = 0x26, .green = 0x26, .blue = 0x26}, 
			{ .red = 0x86, .green = 0x86, .blue = 0x86}, 

};





#endif /*CHANNEL_COLAPSE_H_*/