/*
 * bitmaps.h
 *
 *Generated by Matlab using the scripts in the Tools Folder
 */ 


	//Provides an easy way to include all bitmaps


#ifndef BITMAPS_H_
#define BITMAPS_H_


#include "TS_logo.h"
#include "channel_colapse.h"
#include "channel_perm.h"
#include "channel_temp.h"
#include "icon_default.h"
#include "icon_password.h"
#include "rssi_0.h"
#include "rssi_1.h"
#include "rssi_2.h"
#include "rssi_3.h"
#include "server.h"
#include "user_afk.h"
#include "user_mic_bad.h"
#include "user_mic_mute.h"
#include "user_quite.h"
#include "user_sound_mute.h"
#include "user_speaking.h"


#endif /*BITMAPS_H_*/