/*
 * bitmaps.h
 *
 *Generated by Matlab using the scripts in the Tools Folder
 */ 


		 //Provides an easy way to include all bitmaps


#ifndef BITMAPS_H_
#define BITMAPS_H_


#include "JDBt.h"
#include "TS_logo.h"
#include "speak_light_off.h"
#include "speak_light_on.h"
#include "test.h"


#endif /*BITMAPS_H_*/